### ISSUE TITLE
EAN sets a 14th number on the end

### ISSUE THREAD

**Issue by KAISERslin** [rlt3/php-barcode#3]
Hey,

after a long time using ashberg I crossed something weird on a new system setup with that variation.
A 14th random number at the end of an EAN code. Seems to be cut off and that's why no ending big lines will appear on the false 14th number's end.

So the input is a 12 digit number, but how should I provide a 13 digit EAN?
Is it even supported?

**Examples:**
**EAN:** 4250595829746
**EAN:** 4250595847153

Also tested on a fresh uploaded version with the same "error":
/barcode.php?code=4250595829746

Any idea what happened here or how I can use the system for a 13 digit number input?

**Comment by rlt3** [comment]
13 digit ean barcodes aren't supported

**Comment by wayfarerdb** [comment]
It had been so long that I forgot the 13th digit was the checksum but the old files I found took care of the issue. I committed those files if you hadn't figured something out in the last year or so.
